### ISSUE TITLE
consumer.rb is returns error when hitting `ruby consumer.rb start`

### ISSUE THREAD

**Issue by utmishra** [octoai/apiconsumer#5]
On running `lang=bash; ruby consumer.rb start`, I get the following error:

`Loading from Config file: /path/to/octo/apiconsumer/config/config/config.yml`
`Loading from Config file: /path/to/octo/apiconsumer/config/config/kong_config.yml`
`Loading from Config file: /path/to/octo/apiconsumer/config/config.yml`
`~/.rvm/gems/ruby-2.1.5/gems/kafka-consumer-0.1.3/lib/kafka/consumer.rb:126:in` `manage_partition_consumers': undefined method length' for nil:NilClass (NoMethodError)`
`from ~/.rvm/gems/ruby-2.1.5/gems/kafka-consumer-0.1.3/lib/kafka/consumer.rb:88:in block in each'`

**Comment by pranny** [comment]
This could happen because the topic `events` is not created in kafka. There are two ways here
- You can create topic `events` with default configuration.

``` bash
$ bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic events
```
- You can run `fakestream`. This would push the messages into that topic and it would be created then.

**Comment by pranny** [comment]
@utmishra were above tip able to resolve your issue? If yes, feel free to close the issue

**Comment by utmishra** [comment]
Ran the consumer after fixing few kafka issues, and receive following response. There were no errors. I think it works. Any way to confirm ?

```
administrators-MacBook-Pro-52:apiconsumer utkarsh.mishra$ ruby consumer.rb start
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/apiconsumer/config/config/config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/apiconsumer/config/config/kong_config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/apiconsumer/config/config.yml
```

**Comment by pranny** [comment]
You should be able to see the processes by running `ruby consumer.rb status`. Also check in the logfile.

**Comment by utmishra** [comment]
Log file is not created. Also `ruby consumer.rb status` gave this response. I confirmed that the topic was created.

```
administrators-MacBook-Pro-52:apiconsumer utkarsh.mishra$ ruby consumer.rb status
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/apiconsumer/config/config/config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/apiconsumer/config/config/kong_config.yml
Loading from Config file: /Users/utkarsh.mishra/dev/tools/octo/apiconsumer/config/config.yml
/Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/kafka-consumer-0.1.3/lib/kafka/consumer.rb:126:in `manage_partition_consumers': undefined method `length' for nil:NilClass (NoMethodError)
    from /Users/utkarsh.mishra/.rvm/gems/ruby-2.1.5/gems/kafka-consumer-0.1.3/lib/kafka/consumer.rb:88:in `block in each'
```

**Comment by pranny** [comment]
There was a change introduced last week (again in favor of docker) which broke this process running into demonised mode. It has been reverted now, so a `pull` and then `consumer.rb start|status|stop`  should be working with the logfiles and all. Created a new branch for docker now.

**Comment by utmishra** [comment]
Yes, it works now. Closing the issue.
Thanks!
